### PR TITLE
chore: change hw sdk to forked one

### PR DESCRIPTION
**Pull request by homura**
https://github.com/Magickbase/neuron-public-issues/issues/433

This pull request partially addresses the issue, enabling Ledger to work with Neuron with the `data2` address

It should be manually verified

### CODE REVIEW

**Review by yanguoyu — APPROVED** [review]

**Review by Keith-CY — APPROVED** [review]

**Comment by homura** [comment]
@silySuper could you check if this build is compatible with `data2` addresses

**Comment by homura** [comment]
The merge target has been changed to `update-ckb-client-version` to ensure the CKB client supports `data2` scripts.

**Comment by silySuper** [comment]
verified

**Pull request merged**
