### PR TITLE
fix: Remove unexpected value in log

### PR DESCRIPTION
**Pull request by yanguoyu**

### CODE REVIEW

**Review by Keith-CY — APPROVED** [review]

**Review by homura — APPROVED** [review]

**Comment by yanguoyu** [comment]
> fix: Remove unexpected value in log

fixed

**Comment by silySuper** [comment]
When import same extened public key and not watch wallet(which was created by keystore) it shows 
截屏2024-08-07 09 51 24

video:

https://github.com/user-attachments/assets/9c8fb822-81d2-4576-80fa-1ea12fadbefb


But  not watch wallet in expect it should shows:
截屏2024-08-06 17 35 20

**Comment by yanguoyu** [comment]
> When import same extened public key and not watch wallet(which was created by keystore) it shows 截屏2024-08-07 09 51 24
> 
> video:
> 
>  2024-08-07.09.53.31.mov 
> But not watch wallet in expect it should shows: 截屏2024-08-06 17 35 20

When importing a duplicate watched wallet, from https://github.com/nervosnetwork/neuron/pull/3214#issue-2434082807 this video always shows `replace it`.

**Comment by yanguoyu** [comment]
> When import same extened public key and not watch wallet(which was created by keystore) it shows 截屏2024-08-07 09 51 24
> 
> video:
> 
>  2024-08-07.09.53.31.mov 
> But not watch wallet in expect it should shows: 截屏2024-08-06 17 35 20

fixed

**Review by silySuper — APPROVED** [review]

**Comment by yanguoyu** [comment]
@Keith-CY @homura @devchenyan Please have a review

**Review by Keith-CY — APPROVED** [review]

**Review by homura — APPROVED** [review]

**Pull request merged**
