### PR TITLE
ci: add an action to check spell

### PR DESCRIPTION
**Pull request by Keith-CY**
[fix-spell](https://github.com/nervosnetwork/neuron/tree/fix-spell) is a branch to fix spells in this project, there'll be two steps:

1. add a ci to check spell of changed files
2. fix spells according to the prompts from ci added in step 1

Step 2 will be implemented on [fix-spell](https://github.com/nervosnetwork/neuron/tree/fix-spell)

### CODE REVIEW

**Comment by WhiteMinds** [comment]
This is the draft pr?

**Comment by Keith-CY** [comment]
> This is the draft pr?

It's a PR ready for review.

This PR will be merged into an intermediate branch named `fix-spell` to enable CI for checking spells. And fix of spells will be done on `fix-spell` branch, then the commit of CI and commit of fixing typos will be proposed by merging `fix-spell` into `develop`

**Review by yanguoyu — APPROVED** [review]

**Comment by homura** [comment]
Will we use the correction feature of `typos`? If we don't use this feature, I think we can do [incremental checks](https://github.com/tj-actions/changed-files) so that we can avoid a situation where a large PR is difficult to review

Here is the pseudocode

```yml
- name: Get changed files in the docs folder
  id: changed-files
  uses: tj-actions/changed-files@v36
  with:
    files: *.{md,ts,tsx,js,html}
- uses: crate-ci/typos@master
  with:
    - files: ${{ steps.changed-files.outputs.all_changed_files }}
```

**Comment by Keith-CY** [comment]
> Will we use the correction feature of `typos`? If we don't use this feature, I think we can do [incremental checks](https://github.com/tj-actions/changed-files) so that we can avoid a situation where a large PR is difficult to review
> 
> Here is the pseudocode
> 
> ```yaml
> - name: Get changed files in the docs folder
>   id: changed-files
>   uses: tj-actions/changed-files@v36
>   with:
>     files: *.{md,ts,tsx,js,html}
> - uses: crate-ci/typos@master
>   with:
>     - files: ${{ steps.changed-files.outputs.all_changed_files }}
> ```

I didn't see a parameter to specify files to check. But there's a `--no-check-files` to skip files.

**Comment by homura** [comment]
> I didn't see a parameter to specify files to check. But there's a `--no-check-files` to skip files.

I didn't see it in docs too, I found it the in the [source code](https://github.com/crate-ci/typos/blob/master/action.yml#L5-L8)

**Comment by Keith-CY** [comment]
> > I didn't see a parameter to specify files to check. But there's a `--no-check-files` to skip files.
> 
> I didn't see it in docs too, I found it the in the [source code](https://github.com/crate-ci/typos/blob/master/action.yml?rgh-link-date=2023-06-12T14%3A27%3A00Z#L5-L8)

It prints files to be checked for debug https://github.com/crate-ci/typos#debugging

**Comment by homura** [comment]
> It prints files to be checked for debug [crate-ci/typos#debugging](https://github.com/crate-ci/typos#debugging)

I guess the parameters in GitHub action is not same with the CLI's, the `files` field may be transformed to something like `typos file1 file2 file3...` in the GitHub action

**Comment by homura** [comment]
> > It prints files to be checked for debug [crate-ci/typos#debugging](https://github.com/crate-ci/typos#debugging)
> 
> I guess the parameters in GitHub action is not same with the CLI's, the `files` field may be transformed to something like `typos file1 file2 file3...` in the GitHub action

The parameter transformation can be found in the [entrypoint](https://github.com/crate-ci/typos/blob/master/action/entrypoint.sh#L16)

**Comment by Keith-CY** [comment]
> > It prints files to be checked for debug [crate-ci/typos#debugging](https://github.com/crate-ci/typos#debugging)
> 
> I guess the parameters in GitHub action is not same with the CLI's, the `files` field may be transformed to something like `typos file1 file2 file3...` in the GitHub action

Indeed, `files` is added by https://github.com/nervosnetwork/neuron/pull/2710/commits/3d1011ee958513217639f8efa218acc7304a3095 and an action run for demo can be found at https://github.com/nervosnetwork/neuron/actions/runs/5246056981

**Review by homura — APPROVED** [review]
LGTM

**Review by WhiteMinds — APPROVED** [review]

**Pull request merged**
