### PR TITLE
chore: upgrade dependencies

### PR DESCRIPTION
**Pull request by Keith-CY**
The following dependencies are going to be updated

| Verification State | Dep Name&Desc                                     |
| ------------------ | ------------------------------------------------- |
| ✅                 | @babel/core                                       |
| ✅                 | @babel/node                                       |
| ✅                 | concurrently                                      |
| ✅                 | lerna                                             |
| ✅                 | lint-staged                                       |
| ✅                 | prettier                                          |
| ✅                 | wait-on                                           |
| ✅                 | @babel/plugin-proposal-private-property-in-object |
| ✅                 | @types/react                                      |
| ❓                 | <del>usb</del>                                    |
| ✅                 | @types/enzyme                                     |
| ✅                 | @types/react-dom                                  |
| ✅                 | @electron/notarize                                |
| ✅                 | @types/async                                      |
| ✅                 | @nervosnetwork/ckb-types                          |

Note: Dependency `usb` should be verified @FrederLu who has a hardware wallet, so an approval from @FrederLu is required

### CODE REVIEW

**Comment by Keith-CY** [comment]
This PR updates dependencies and has nothing to do with functionalities, please have a review
@zhangyouxin @homura @WhiteMinds @devchenyan @yanguoyu @JeffreyMa597

Verification of `usb` and `@ledgerhq/hw-transport-node-hid` requires the hardware wallet, need help from @FrederLu

**Comment by FrederLu** [comment]
After linking `Ledger`, using Neuron transaction or adding a hardware wallet prompts that the connection cannot be recognized.
image
image

**Comment by yanguoyu** [comment]
> > Packaging for test is done in [5319344416](https://github.com/nervosnetwork/neuron/actions/runs/5319344416) for commit [4de2324](https://github.com/nervosnetwork/neuron/commit/4de2324908772377d98c4e6bc0fdf58789073020) .
> 
> After linking `Ledger`, using Neuron transaction or adding a hardware wallet prompts that the connection cannot be recognized. image image

The nano s plus also happens like that, I will check what causes that.

**Comment by Keith-CY** [comment]
> > Packaging for test is done in [5319344416](https://github.com/nervosnetwork/neuron/actions/runs/5319344416) for commit [4de2324](https://github.com/nervosnetwork/neuron/commit/4de2324908772377d98c4e6bc0fdf58789073020) .
> 
> After linking `Ledger`, using Neuron transaction or adding a hardware wallet prompts that the connection cannot be recognized. image image

The updates on `new-ui-design` has been merged into this PR, please check if it works @FrederLu

**Comment by FrederLu** [comment]
> > > Packaging for test is done in [5319344416](https://github.com/nervosnetwork/neuron/actions/runs/5319344416) for commit [4de2324](https://github.com/nervosnetwork/neuron/commit/4de2324908772377d98c4e6bc0fdf58789073020) .
> > 
> > 
> > After linking `Ledger`, using Neuron transaction or adding a hardware wallet prompts that the connection cannot be recognized. image image
> 
> The updates on `new-ui-design` has been merged into this PR, please check if it works @FrederLu

Packaging seems to be abnormal.

**Comment by Keith-CY** [comment]
> > > > Packaging for test is done in [5319344416](https://github.com/nervosnetwork/neuron/actions/runs/5319344416) for commit [4de2324](https://github.com/nervosnetwork/neuron/commit/4de2324908772377d98c4e6bc0fdf58789073020) .
> > > 
> > > 
> > > After linking `Ledger`, using Neuron transaction or adding a hardware wallet prompts that the connection cannot be recognized. image image
> > 
> > 
> > The updates on `new-ui-design` has been merged into this PR, please check if it works @FrederLu
> 
> Packaging seems to be abnormal.

It's still being packaged at https://github.com/nervosnetwork/neuron/actions/runs/5320762602?pr=2724

**Comment by FrederLu** [comment]
> Packaging for test is done in [5326399680](https://github.com/nervosnetwork/neuron/actions/runs/5326399680) for commit [40a4d2e](https://github.com/nervosnetwork/neuron/commit/40a4d2e6e7cdee6a87dc61d5e38d6a328adbc2d2) .

**This package is still unable to connect.**
image
image

**Comment by FrederLu** [comment]
link :https://github.com/nervosnetwork/neuron/pull/2716#issuecomment-1588684289
The packages linked above are linkable.
image

**Comment by yanguoyu** [comment]
The node module `usb` in `@ledgerhq/hw-transport-node-hid`'s dependencies is `^1.7.0`.
Maybe we can remove the resolutions of `usb`. I have checked `import hard wallet` and `send ckb from hard wallet`.

**Comment by Keith-CY** [comment]
Does `remove the resolutions of usb` mean removing it from this PR, or removing it from the dependencies

**Comment by yanguoyu** [comment]
> Does `remove the resolutions of usb` mean removing it from this PR, or removing it from the dependencies

I mean removing it from the dependencies, but we'd better check whether it works in M1 because of https://github.com/nervosnetwork/neuron/pull/2541.

**Comment by Keith-CY** [comment]
> > Does `remove the resolutions of usb` mean removing it from this PR, or removing it from the dependencies
> 
> I mean removing it from the dependencies, but we'd better check whether it works in M1 because of #2541.

I see, the update of `usb` will be removed from this PR first

**Comment by FrederLu** [comment]
> Packaging for test is done in [5333094886](https://github.com/nervosnetwork/neuron/actions/runs/5333094886) for commit [b8e6d3c](https://github.com/nervosnetwork/neuron/commit/b8e6d3c27fee2a39c0aa77911ec618eeec5d3a46) .

This package can be connected and signed using `Ledger Nano X`.

**Review by FrederLu — APPROVED** [review]

**Review by homura — APPROVED** [review]
LGTM

**Pull request merged**
