### PR TITLE
Adopt new UI

### PR DESCRIPTION
**Pull request by Keith-CY**
Design: https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?node-id=319%3A4539

### CODE REVIEW

**Comment by Cedar67** [comment]
Does this merge mean that the new UI function (`Create new wallet`) will be released to users?

**Comment by Keith-CY** [comment]
> Does this merge mean that the new UI function (`Create new wallet`) will be released to users?

Not now, it's a draft PR to show the progress of adopting new UI and will not be merged until the UI is fully polished and tested in the `new-ui-design` branch.

**Comment by Cedar67** [comment]
> > Does this merge mean that the new UI function (`Create new wallet`) will be released to users?
> 
> Not now, it's a draft PR to show the progress of adopting new UI and will not be merged until the UI is fully polished and tested in the `new-ui-design` branch.

got it.

**Comment by Keith-CY** [comment]
We'd better resolve the conflicts first @devchenyan

**Comment by devchenyan** [comment]
> We'd better resolve the conflicts first @devchenyan

https://github.com/nervosnetwork/neuron/pull/2654

**Pull request merged**
