### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by Keith-CY**
The following dependencies are going to be updated.

| Verification State | Dep Name&Desc                   |
| ------------------ | ------------------------------- |
| ✅                 | @types/archiver                 |
| ✅                 | @types/node                     |
| ✅                 | @types/npmlog                   |
| ✅                 | archiver                        |
| ✅                 | electron                        |
| ✅                 | electron-builder                |
| ✅                 | eslint-config-prettier          |
| ✅                 | github/codeql-action/analyze    |
| ✅                 | github/codeql-action/autobuild  |
| ✅                 | github/codeql-action/init       |
| ✅                 | lerna                           |
| ✅                 | lint-staged                     |
| ✅                 | peter-evans/commit-comment      |
| ✅                 | react-router-dom                |
| ✅                 | storybook-addon-react-router-v6 |
| ✅                 | tj-actions/changed-files        |

### CODE REVIEW

**Review by yanguoyu — APPROVED** [review]

**Comment by Keith-CY** [comment]
Please have a review @zhangyouxin @homura @WhiteMinds @devchenyan

**Review by homura — APPROVED** [review]
LGTM

**Pull request merged**
