### PR TITLE
refactor: i18n key

### PR DESCRIPTION
**Pull request by BaojunCZ**

### CODE REVIEW

**Comment by Keith-CY** [comment]
According to the [docs](https://react.i18next.com/latest/usetranslation-hook), namespace can be a param of `useTranslation`

**Comment by BaojunCZ** [comment]
get it

**Comment by ashchan** [comment]
> According to the [docs](https://react.i18next.com/latest/usetranslation-hook), namespace can be a param of `useTranslation`

`t('path.to.key')` usage is fine.

**Comment by BaojunCZ** [comment]
Uniform format or both？I don’t think it has much impact.

**Comment by ashchan** [comment]
> Uniform format or both？I don’t think it has much impact.

Use full path format if possible. Example:

https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/menu.ts#L27

**Comment by BaojunCZ** [comment]
ok,I will use full path format and make keys to be lower cases

**Pull request merged**
