### PR TITLE
fix: Fix socket hang

### PR DESCRIPTION
**Pull request by yanguoyu**
Refer to https://github.com/Magickbase/neuron-public-issues/issues/389

### CODE REVIEW

**Comment by twhy** [comment]
@Keith-CY Please prioritize this PR for review and merge because the related issue may block syncing.

**Comment by silySuper** [comment]
Can not sync ,always show sync not start yet.
截屏2024-05-09 10 38 47
[main.log](https://github.com/nervosnetwork/neuron/files/15256900/main.log)
 
node log:
截屏2024-05-09 10 40 56
截屏2024-05-09 10 39 22

**Review by Keith-CY — APPROVED** [review]

**Comment by yanguoyu** [comment]
> Can not sync ,always show sync not start yet. 截屏2024-05-09 10 38 47 [main.log](https://github.com/nervosnetwork/neuron/files/15256900/main.log)
> 
> node log: 截屏2024-05-09 10 40 56 截屏2024-05-09 10 39 22

Hi, do you use the package from https://github.com/nervosnetwork/neuron/actions/runs/8983636524? I had no issues with `socket hang` after using this package.

**Comment by silySuper** [comment]
> > Can not sync ,always show sync not start yet. 截屏2024-05-09 10 38 47 [main.log](https://github.com/nervosnetwork/neuron/files/15256900/main.log)
> > node log: 截屏2024-05-09 10 40 56 截屏2024-05-09 10 39 22
> 
> Hi, do you use the package from https://github.com/nervosnetwork/neuron/actions/runs/8983636524? I had no issues with `socket hang` after using this package. @silySuper

yes,i am using this package

**Comment by homura** [comment]
Sorry for replying late. I wanted to let you know that starting from lumos@0.21, you can now customize the fetch of the package `@ckb-lumos/rpc` using https://github.com/ckb-js/lumos/pull/574. You can achieve this by using the following code:

```ts
new RPC('https...', { fetch: globalThis.fetch })
```

I suggest trying out the NodeJS's native fetch, which is stable from Node@21, although Neuron is currently using [Node@220.11.1](https://www.electronjs.org/blog/electron-30-0).

**Comment by yanguoyu** [comment]
> Sorry for replying late. I wanted to let you know that starting from lumos@0.21, you can now customize the fetch of the package `@ckb-lumos/rpc` using [ckb-js/lumos#574](https://github.com/ckb-js/lumos/pull/574). You can achieve this by using the following code:
> 
> ```ts
> new RPC('https...', { fetch: globalThis.fetch })
> ```
> 
> I suggest trying out the NodeJS's native fetch, which is stable from Node@21, although Neuron is currently using [Node@220.11.1](https://www.electronjs.org/blog/electron-30-0).

Hi, the `Indexer` constructor doesn't have the `fetch` option. And the Neuron throws `socket hang` at https://github.com/nervosnetwork/neuron/blob/v0.114.3/packages/neuron-wallet/src/block-sync-renderer/sync/indexer-cache-service.ts#L81.

**Comment by homura** [comment]
> Hi, the Indexer constructor doesn't have the fetch option. And the Neuron throws socket hang at

Lumos needs to allow for customizing the `fetch` function in the `Indexer`. Therefore, the `node-fetch` override is still necessary now

**Review by homura — APPROVED** [review]

**Comment by silySuper** [comment]
ckb node V114.0 to run 108 data can not sync,I tried ckb node v115 can sync

**Review by devchenyan — APPROVED** [review]

**Comment by yanguoyu** [comment]
@silySuper This PR should be merged first, it will block testing other PRs that use full-node synchronized

**Comment by silySuper** [comment]
截屏2024-05-14 11 24 58

new data can sync ,but old data can not sync in my computer

**Comment by yanguoyu** [comment]
> 截屏2024-05-14 11 24 58
> new data can sync ,but old data can not sync in my computer

From your provider log, your old data has broken. I guess it's normal because your ckb node can't run success with old data.

**Comment by silySuper** [comment]
socket hang   fix verified

**Review by silySuper — APPROVED** [review]

**Pull request merged**
