### PR TITLE
fix: Multisig address sync tip language

### PR DESCRIPTION
**Pull request by devchenyan**
issue: https://github.com/Magickbase/neuron-public-issues/issues/405

image

### CODE REVIEW

**Review by yanguoyu — APPROVED** [review]

**Comment by yanguoyu** [comment]
I guess this PR does not fix this bug.

**Comment by Danie0918** [comment]
@homura @twhy Please have a review.

**Comment by Danie0918** [comment]
@homura  Please have a review.

**Review by homura — APPROVED** [review]

**Review by silySuper — APPROVED** [review]

**Pull request merged**
