### PR TITLE
refactor: fix typos

### PR DESCRIPTION
**Pull request by Keith-CY**
This PR adds a CI to check spelling and fixes existing typos

1. add CI to check spelling https://github.com/nervosnetwork/neuron/pull/2710
2. fix typos in neuron-ui https://github.com/nervosnetwork/neuron/pull/2739
3. fix typos in neuron-wallet https://github.com/nervosnetwork/neuron/pull/2740
4. fix a typo introduced from develop branch https://github.com/nervosnetwork/neuron/pull/2738/commits/68ab465db04036f472d38aa54dea8e21841f18b9
5. ignore `Changelog.md` because unexpected fixes are adopted to `commit hash` https://github.com/nervosnetwork/neuron/pull/2738/commits/2edbf599efb03de1f280d26835605f7353ebb5fe

---

Affected `i18n keys`:
1. `receive.turn-into-full-version-fomrat`, the tooltip on multisig receive dialog: https://github.com/nervosnetwork/neuron/pull/2738/files#diff-3b9155793b46abe9ea620cb1f3b80968b54c8acd7d9c56b6dc9e6b315af24aaaL155
2. `receive.turn-into-full-version-fomrat`, the tooltip on the sudt receive page : https://github.com/nervosnetwork/neuron/pull/2738/files#diff-da651da5431b8fe1c078b351d17c20d295adb545e64adfb4f98d1e793ff84fb2L70
3. `messages.transaction-no-input-paramter` when a generated transaction is invalid due to empty input list : https://github.com/nervosnetwork/neuron/pull/2738/files#diff-0bea1639d55e771c87f6c3bb5278ca422e8e8de073007efa93a250016f4da9ebL23

### CODE REVIEW

**Comment by Keith-CY** [comment]
Hold on, `changelog` should be ignored in the CI

**Comment by Keith-CY** [comment]
CHANGELOG.md is excluded from the check list because it includes many commit hashes which are mistakenly fixed by `typos`

Please have a review @yanguoyu @WhiteMinds @devchenyan @JeffreyMa597 @homura @zhangyouxin

**Comment by Keith-CY** [comment]
> the PR is LGTM, but I suggest the PR needs to check all the i18n text are working well on the user interface

I'll list the modified `i18n key` for review from testers

**Comment by Keith-CY** [comment]
The affected `i18n keys` have been updated in the PR message

> Affected `i18n keys`:
> 1. `receive.turn-into-full-version-fomrat`, the tooltip on multisig receive dialog: https://github.com/nervosnetwork/neuron/pull/2738/files#diff-3b9155793b46abe9ea620cb1f3b80968b54c8acd7d9c56b6dc9e6b315af24aaaL155
> 2. `receive.turn-into-full-version-fomrat`, the tooltip on the sudt receive page : https://github.com/nervosnetwork/neuron/pull/2738/files#diff-da651da5431b8fe1c078b351d17c20d295adb545e64adfb4f98d1e793ff84fb2L70
> 3. `messages.transaction-no-input-paramter` when a generated transaction is invalid due to empty input list : https://github.com/nervosnetwork/neuron/pull/2738/files#diff-0bea1639d55e771c87f6c3bb5278ca422e8e8de073007efa93a250016f4da9ebL23

1 and 2 can be verified on UI, while 3 is hard to reproduce but it's an error message for developers and can be omitted for UI

Please have a review @FrederLu @silySuper @littleLip520

**Review by yanguoyu — APPROVED** [review]

**Review by zhangyouxin — APPROVED** [review]

**Pull request merged**
