### PR TITLE
feat: update tx description

### PR DESCRIPTION
**Pull request by classicalliu**

### CODE REVIEW

**Comment by Keith-CY** [comment]
@ashchan how to show the alert of the failure to update transaction descriptions?

**Comment by classicalliu** [comment]
`description` will not show on UI layer (can update, but still show empty) @Keith-CY

**Comment by Keith-CY** [comment]
> `description` will not show on UI layer (can update, but still show empty) @Keith-CY

It is displayed in the transaction list.

**Comment by classicalliu** [comment]
> > `description` will not show on UI layer (can update, but still show empty) @Keith-CY
> 
> It is displayed in the transaction list.

I means `description` in transaction list is still empty, not read the real data.
You can try after this merged.

**Comment by classicalliu** [comment]
I found the problem, I'll fix @Keith-CY

**Comment by ashchan** [comment]
> @ashchan how to show the alert of the failure to update transaction descriptions?

This should not happen in normal use. When does this happen?

**Pull request merged**
