### PR TITLE
Release v0.114.3

### PR DESCRIPTION
**Pull request by Keith-CY**
# 0.114.3 (2024-04-16)

### CKB Node & Light Client

- [CKB@v0.114.0](https://github.com/nervosnetwork/ckb/releases/tag/v0.114.0) was released on Feb. 29st, 2024. This version of CKB node is now bundled and preconfigured in Neuron.
- [CKB Light Client@v0.3.7](https://github.com/nervosnetwork/ckb-light-client/releases/tag/v0.3.7) was released on Apr. 13th, 2024. This version of CKB Light Client is now bundled and preconfigured in Neuron

### Assumed valid target

Block before `0x9443ad8da9172d484367bc5467988cba7a0c46028398309edfdda7d2d79be897`(at height `12,703,957`) will be skipped in validation.(https://github.com/nervosnetwork/neuron/pull/3123)

---

## New features

- #3054: Displaying DAO rewards.(@devchenyan)
- #3066: Support keeping screen awake.(@yanguoyu)

## Bug fixes

- #3055: Fix sending sudt to a new acp cell with extra 142 CKB by offline sign.(@yanguoyu)
- #3103: Handle MacOS crash properly on quitting.(@devchenyan)

## New Contributors

- @twhy made their first contribution in https://github.com/nervosnetwork/neuron/pull/3110

**Full Changelog**: https://github.com/nervosnetwork/neuron/compare/v0.114.2...v0.114.3

### CODE REVIEW

**Review by yanguoyu — APPROVED** [review]

**Comment by Danie0918** [comment]
@devchenyan Please have a review.

**Review by devchenyan — APPROVED** [review]

**Comment by yanguoyu** [comment]
> /package

For the RC branch, it will trigger by push event. So we can get the package at https://github.com/nervosnetwork/neuron/actions/workflows/package_for_test.yml?query=event%3Apush+branch%3Arc%2Fv0.114.3

**Comment by silySuper** [comment]
> > /package
> 
> For the RC branch, it will trigger by push event. So we can get the package at https://github.com/nervosnetwork/neuron/actions/workflows/package_for_test.yml?query=event%3Apush+branch%3Arc%2Fv0.114.3

**Comment by yanguoyu** [comment]
Reopen at https://github.com/nervosnetwork/neuron/pull/3127

**Pull request closed without merging**
