### PR TITLE
chore(e2e): Add network e2e test

### PR DESCRIPTION
**Pull request by cezres**
- Add network e2e test https://github.com/nervosnetwork/neuron/pull/876/commits/2e1bfb84cc021437ca8068f9a682d86a5707268c, https://github.com/nervosnetwork/neuron/pull/876/commits/52522f6566aad57c187ce87b7e59e290c00b02df
- Save screenshot/log of the test error https://github.com/nervosnetwork/neuron/pull/876/commits/4fb5cdeb4c4b66ca58e79ea3101acd53eaffaaa8
- Retry after element query failed https://github.com/nervosnetwork/neuron/pull/876/commits/5a641d12c0a69b2ea61c39d18e36c567f5961a3e

### CODE REVIEW

**Comment by ashchan** [comment]
> * Save screenshot/log of the test error [4fb5cde](https://github.com/nervosnetwork/neuron/commit/4fb5cdeb4c4b66ca58e79ea3101acd53eaffaaa8)

How do we access these screenshots from Azure Pipelines?

**Comment by cezres** [comment]
> > * Save screenshot/log of the test error [4fb5cde](https://github.com/nervosnetwork/neuron/commit/4fb5cdeb4c4b66ca58e79ea3101acd53eaffaaa8)
> 
> How do we access these screenshots from Azure Pipelines?

I don't know how to access these screenshots, but it is useful locally.
And it is also to skip the next test in case of an error.

**Comment by ashchan** [comment]
I see. That makes sense.

**Comment by cezres** [comment]
@ashchan  Only one test app will be launched now. https://github.com/nervosnetwork/neuron/pull/876/commits/afc787279f68c4fc162f64c84a8887d31c8f2366

**Pull request merged**
