### PR TITLE
- Support Arabic, FrCanadian/Belgian in User Interface 

### PR DESCRIPTION
**Pull request by Natixe**
- Support Arabic in User Interface
- Support French Canadian in User Interface
- Support French Belgian in User Interface

### CODE REVIEW

**Comment by Keith-CY** [comment]
Hi @Natixe, truly appreciate your contribution to this project, we will start the review shortly.

**Comment by Danie0918** [comment]
@homura @yanguoyu @devchenyan  Please have a review.

**Comment by Natixe** [comment]
Thanks @Keith-CY I really like the project and ckb so I'm participating ;)

**Comment by Keith-CY** [comment]
I found the CI was blocked, any suggestions from @yanguoyu @homura

**Comment by yanguoyu** [comment]
> I found the CI was blocked, any suggestions from @yanguoyu @homura

It looks like the `neuron-ui` package test run failed.
https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271

```
FAIL   UI Tests  src/tests/calendar/index.test.ts
    ● Get Local Month Short Names › Arabic
  
      expect(received).toEqual(expected) // deep equality
  
      - Expected  - 12
      + Received  + 12
  
        Array [
      -   "ينا.",
      -   "فبر.",
      -   "مارس.",
      -   "أبر.",
      -   "مايو.",
      -   "يون.",
      -   "يول.",
      -   "أغس.",
      -   "سبت.",
      -   "أكت.",
      -   "نوف.",
      -   "ديس.",
      +   "يناير",
      +   "فبراير",
      +   "مارس",
      +   "أبريل",
      +   "مايو",
      +   "يونيو",
      +   "يوليو",
      +   "أغسطس",
      +   "سبتمبر",
      +   "أكتوبر",
      +   "نوفمبر",
      +   "ديسمبر",
        ]
  
        114 |   it('Arabic', () => {
        115 |     const names = ['ينا.', 'فبر.', 'مارس.', 'أبر.', 'مايو.', 'يون.', 'يول.', 'أغس.', 'سبت.', 'أكت.', 'نوف.', 'ديس.']
      > 116 |     expect(getLocalMonthShortNames('ar')).toEqual(names)
            |                                           ^
        117 |   })
        118 |
        119 |   it('Spanish', () => {
  
        at Object.<anonymous> (src/tests/calendar/index.test.ts:116:43)
  
    ● Get Local Week Names › Arabic
  
      expect(received).toEqual(expected) // deep equality
  
      - Expected  - 2
      + Received  + 2
  
        Array [
          "ح",
      -   "إ",
      +   "ن",
          "ث",
      -   "أ",
      +   "ر",
          "خ",
          "ج",
          "س",
        ]
  
        [22](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:23)3 |   it('Arabic', () => {
        224 |     const names = ['ح', 'إ', 'ث', 'أ', 'خ', 'ج', 'س']
      > 2[25](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:26) |     expect(getLocalWeekNames('ar')).toEqual(names)
            |                                     ^
        2[26](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:27) |   })
        2[27](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:28) |
        228 |   it('Traditional Chinese', () => {
  
        at Object.<anonymous> (src/tests/calendar/index.test.ts:225:[37](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:38))
```

**Comment by Keith-CY** [comment]
> > I found the CI was blocked, any suggestions from @yanguoyu @homura
> 
> It looks like the `neuron-ui` package test run failed. [nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271)
> 
> ```
> FAIL   UI Tests  src/tests/calendar/index.test.ts
>     ● Get Local Month Short Names › Arabic
>   
>       expect(received).toEqual(expected) // deep equality
>   
>       - Expected  - 12
>       + Received  + 12
>   
>         Array [
>       -   "ينا.",
>       -   "فبر.",
>       -   "مارس.",
>       -   "أبر.",
>       -   "مايو.",
>       -   "يون.",
>       -   "يول.",
>       -   "أغس.",
>       -   "سبت.",
>       -   "أكت.",
>       -   "نوف.",
>       -   "ديس.",
>       +   "يناير",
>       +   "فبراير",
>       +   "مارس",
>       +   "أبريل",
>       +   "مايو",
>       +   "يونيو",
>       +   "يوليو",
>       +   "أغسطس",
>       +   "سبتمبر",
>       +   "أكتوبر",
>       +   "نوفمبر",
>       +   "ديسمبر",
>         ]
>   
>         114 |   it('Arabic', () => {
>         115 |     const names = ['ينا.', 'فبر.', 'مارس.', 'أبر.', 'مايو.', 'يون.', 'يول.', 'أغس.', 'سبت.', 'أكت.', 'نوف.', 'ديس.']
>       > 116 |     expect(getLocalMonthShortNames('ar')).toEqual(names)
>             |                                           ^
>         117 |   })
>         118 |
>         119 |   it('Spanish', () => {
>   
>         at Object.<anonymous> (src/tests/calendar/index.test.ts:116:43)
>   
>     ● Get Local Week Names › Arabic
>   
>       expect(received).toEqual(expected) // deep equality
>   
>       - Expected  - 2
>       + Received  + 2
>   
>         Array [
>           "ح",
>       -   "إ",
>       +   "ن",
>           "ث",
>       -   "أ",
>       +   "ر",
>           "خ",
>           "ج",
>           "س",
>         ]
>   
>         [22](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:23)3 |   it('Arabic', () => {
>         224 |     const names = ['ح', 'إ', 'ث', 'أ', 'خ', 'ج', 'س']
>       > 2[25](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:26) |     expect(getLocalWeekNames('ar')).toEqual(names)
>             |                                     ^
>         2[26](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:27) |   })
>         2[27](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:28) |
>         228 |   it('Traditional Chinese', () => {
>   
>         at Object.<anonymous> (src/tests/calendar/index.test.ts:225:[37](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:38))
> ```

I will contact the community Mod to help us review the wording to see if we should update our test sets.

**Comment by Keith-CY** [comment]
> > > I found the CI was blocked, any suggestions from @yanguoyu @homura
> > 
> > 
> > It looks like the `neuron-ui` package test run failed. [nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271)
> > ```
> > FAIL   UI Tests  src/tests/calendar/index.test.ts
> >     ● Get Local Month Short Names › Arabic
> >   
> >       expect(received).toEqual(expected) // deep equality
> >   
> >       - Expected  - 12
> >       + Received  + 12
> >   
> >         Array [
> >       -   "ينا.",
> >       -   "فبر.",
> >       -   "مارس.",
> >       -   "أبر.",
> >       -   "مايو.",
> >       -   "يون.",
> >       -   "يول.",
> >       -   "أغس.",
> >       -   "سبت.",
> >       -   "أكت.",
> >       -   "نوف.",
> >       -   "ديس.",
> >       +   "يناير",
> >       +   "فبراير",
> >       +   "مارس",
> >       +   "أبريل",
> >       +   "مايو",
> >       +   "يونيو",
> >       +   "يوليو",
> >       +   "أغسطس",
> >       +   "سبتمبر",
> >       +   "أكتوبر",
> >       +   "نوفمبر",
> >       +   "ديسمبر",
> >         ]
> >   
> >         114 |   it('Arabic', () => {
> >         115 |     const names = ['ينا.', 'فبر.', 'مارس.', 'أبر.', 'مايو.', 'يون.', 'يول.', 'أغس.', 'سبت.', 'أكت.', 'نوف.', 'ديس.']
> >       > 116 |     expect(getLocalMonthShortNames('ar')).toEqual(names)
> >             |                                           ^
> >         117 |   })
> >         118 |
> >         119 |   it('Spanish', () => {
> >   
> >         at Object.<anonymous> (src/tests/calendar/index.test.ts:116:43)
> >   
> >     ● Get Local Week Names › Arabic
> >   
> >       expect(received).toEqual(expected) // deep equality
> >   
> >       - Expected  - 2
> >       + Received  + 2
> >   
> >         Array [
> >           "ح",
> >       -   "إ",
> >       +   "ن",
> >           "ث",
> >       -   "أ",
> >       +   "ر",
> >           "خ",
> >           "ج",
> >           "س",
> >         ]
> >   
> >         [22](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:23)3 |   it('Arabic', () => {
> >         224 |     const names = ['ح', 'إ', 'ث', 'أ', 'خ', 'ج', 'س']
> >       > 2[25](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:26) |     expect(getLocalWeekNames('ar')).toEqual(names)
> >             |                                     ^
> >         2[26](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:27) |   })
> >         2[27](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:28) |
> >         228 |   it('Traditional Chinese', () => {
> >   
> >         at Object.<anonymous> (src/tests/calendar/index.test.ts:225:[37](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:38))
> > ```
> 
> I will contact the community Mod to help us review the wording to see if we should update our test sets.

We should update our test sets based on support from the community. @yanguoyu

And there are some reviews for the rest of the translations, I will append them later.

**Comment by Keith-CY** [comment]
> > > > I found the CI was blocked, any suggestions from @yanguoyu @homura
> > > 
> > > 
> > > It looks like the `neuron-ui` package test run failed. [nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271)
> > > ```
> > > FAIL   UI Tests  src/tests/calendar/index.test.ts
> > >     ● Get Local Month Short Names › Arabic
> > >   
> > >       expect(received).toEqual(expected) // deep equality
> > >   
> > >       - Expected  - 12
> > >       + Received  + 12
> > >   
> > >         Array [
> > >       -   "ينا.",
> > >       -   "فبر.",
> > >       -   "مارس.",
> > >       -   "أبر.",
> > >       -   "مايو.",
> > >       -   "يون.",
> > >       -   "يول.",
> > >       -   "أغس.",
> > >       -   "سبت.",
> > >       -   "أكت.",
> > >       -   "نوف.",
> > >       -   "ديس.",
> > >       +   "يناير",
> > >       +   "فبراير",
> > >       +   "مارس",
> > >       +   "أبريل",
> > >       +   "مايو",
> > >       +   "يونيو",
> > >       +   "يوليو",
> > >       +   "أغسطس",
> > >       +   "سبتمبر",
> > >       +   "أكتوبر",
> > >       +   "نوفمبر",
> > >       +   "ديسمبر",
> > >         ]
> > >   
> > >         114 |   it('Arabic', () => {
> > >         115 |     const names = ['ينا.', 'فبر.', 'مارس.', 'أبر.', 'مايو.', 'يون.', 'يول.', 'أغس.', 'سبت.', 'أكت.', 'نوف.', 'ديس.']
> > >       > 116 |     expect(getLocalMonthShortNames('ar')).toEqual(names)
> > >             |                                           ^
> > >         117 |   })
> > >         118 |
> > >         119 |   it('Spanish', () => {
> > >   
> > >         at Object.<anonymous> (src/tests/calendar/index.test.ts:116:43)
> > >   
> > >     ● Get Local Week Names › Arabic
> > >   
> > >       expect(received).toEqual(expected) // deep equality
> > >   
> > >       - Expected  - 2
> > >       + Received  + 2
> > >   
> > >         Array [
> > >           "ح",
> > >       -   "إ",
> > >       +   "ن",
> > >           "ث",
> > >       -   "أ",
> > >       +   "ر",
> > >           "خ",
> > >           "ج",
> > >           "س",
> > >         ]
> > >   
> > >         [22](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:23)3 |   it('Arabic', () => {
> > >         224 |     const names = ['ح', 'إ', 'ث', 'أ', 'خ', 'ج', 'س']
> > >       > 2[25](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:26) |     expect(getLocalWeekNames('ar')).toEqual(names)
> > >             |                                     ^
> > >         2[26](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:27) |   })
> > >         2[27](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:28) |
> > >         228 |   it('Traditional Chinese', () => {
> > >   
> > >         at Object.<anonymous> (src/tests/calendar/index.test.ts:225:[37](https://github.com/nervosnetwork/neuron/actions/runs/12127893610/job/33894569475?pr=3271#step:9:38))
> > > ```
> > 
> > 
> > I will contact the community Mod to help us review the wording to see if we should update our test sets.
> 
> We should update our test sets based on support from the community. @yanguoyu
> 
> And there are some reviews for the rest of the translations, I will append them later.

With the help of ChatGPT, I found the translation to be pretty good and didn't need to be adjusted.
I would suggest merging this PR first and fixing the test sets from our sides, any idea from @yanguoyu @homura

**Comment by yanguoyu** [comment]
> With the help of ChatGPT, I found the translation to be pretty good and didn't need to be adjusted. I would suggest merging this PR to a specific branch first and fixing the test sets from our sides, any idea from @yanguoyu @homura

No problem

**Comment by homura** [comment]
> With the help of ChatGPT, I found the translation to be pretty good and didn't need to be adjusted.
> I would suggest merging this PR to a specific branch first and fixing the test sets from our sides, any idea from

I also asked Claude, and it told me that this is a high-quality translation

**Comment by Keith-CY** [comment]
I've opened https://github.com/nervosnetwork/neuron/tree/add-more-locales to fix the test sets. Please add approval if no more suggestion @yanguoyu @homura

**Review by homura — APPROVED** [review]

**Review by yanguoyu — APPROVED** [review]

**Comment by Natixe** [comment]
Hey, thank you for the compliments on my translation; I was happy to do it. If you know a native Arabic speaker who can give you feedback, that would be even better. I hope you appreciate my help in any case :) ^^

**Pull request merged**
