### PR TITLE
fix: For windows os the user need to start the Neuron manually after installed.

### PR DESCRIPTION
**Pull request by yanguoyu**
Refer to https://github.com/Magickbase/neuron-public-issues/issues/397#issuecomment-2182108426

### CODE REVIEW

**Review by devchenyan — APPROVED** [review]

**Comment by Danie0918** [comment]
@homura @twhy Please have a review.

**Review by Keith-CY — APPROVED** [review]

**Comment by silySuper** [comment]
截屏2024-06-25 16 41 32

**Comment by yanguoyu** [comment]
> 截屏2024-06-25 16 41 32 截屏2024-06-25 16 50 48

https://github.com/Magickbase/neuron-public-issues/issues/397#issuecomment-2182108426

**Comment by silySuper** [comment]
confirmText={t(`updates.${isWin ? 'quit-and-install-restart' : 'quit-and-install'}`)}
if iswin  true shows quit-and-install-restart，if not shows quit-and-install
actual：
截屏2024-06-26 11 46 24
so when iswin,expect to show relaunch or not ?

**Review by twhy — APPROVED** [review]

**Review by silySuper — APPROVED** [review]

**Pull request merged**
