### PR TITLE
chore: optimize issue template

### PR DESCRIPTION
**Pull request by Keith-CY**
1. Use GitHub's form feature by default;
2. Update submission rules to lead users to help center;
3. Add a field for ckb light client.

---

Preview: https://github.com/nervosnetwork/neuron/blob/optimize-issue-template/.github/ISSUE_TEMPLATE/bug_report.yml

### CODE REVIEW

**Comment by Keith-CY** [comment]
Please check if any other fields should be added for debug

**Review by yanguoyu — APPROVED** [review]

**Comment by Keith-CY** [comment]
Please have a review @Danie0918 @Sven-TBD

**Comment by Danie0918** [comment]
1. Here `Detail of the issue`, `Screenshots` and `Debug information` can be split into 3 modules for more clarity and accessibility.

 `Detail of the issue` : Mandatory option that requires the user to describe the problem through text.
`Screenshots`  : Optional, user uploaded screenshot files.
`Debug information` : Optional, users only need to upload the debug information zip file.

2. Follow-up can be appended to the Help Center website.

**Comment by Keith-CY** [comment]
>    `Screenshots`  : Optional, user uploaded screenshot files.

The annotation of `detail of this issue` was updated to `Please append detail of the issue here, including steps to reproduce, screenshots, etc.` to inform users to upload screenshots.

>    `Detail of the issue` : Mandatory option that requires the user to describe the problem through text.
>    `Debug information` : Optional, users only need to upload the debug information zip file.

I didn't get this because `Detail of the issue` is mandatory and `Debug information` is optional now.

image


> 2. Follow-up can be appended to the Help Center website.

Is this a note for other users to track this issue on Helper Center page?

**Comment by Danie0918** [comment]
> I didn't get this because `Detail of the issue` is mandatory and `Debug information` is optional now.

Here is where it was felt that pasting debug information was not necessary, took up more space, and would increase the cost of use and reading for the user.

Users only need to upload the zip file of debug information.

> Is this a note for other users to track this issue on Helper Center page?

This is something that can be self-checked before a user creates a new issue, reducing duplicate issues.

**Comment by Keith-CY** [comment]
> Here is where it was felt that pasting debug information was not necessary, took up more space, and would increase the cost of use and reading for the user.

I got this. It's intended and optional, as mentioned at https://github.com/nervosnetwork/neuron/pull/2961/files#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efR44

Uploading a zip file is easy for users, but pasting debug information into an issue facilitates searching. Similar issues could be hit when users search for a snippet of log, e.g. https://github.com/search?q=repo%3Anervosnetwork%2Fneuron+ckb_memory_tracker%3A%3Aprocess&type=issues


> This is something that can be self-checked before a user creates a new issue, reducing duplicate issues.

It has been mentioned at the start https://github.com/nervosnetwork/neuron/pull/2961/files#diff-637f7b97bba458badb691a1557c3d4648686292e948dbe3e8360564378b653efR13

**Review by Danie0918 — APPROVED** [review]

**Pull request merged**
