### PR TITLE
Bump some deps

### PR DESCRIPTION
**Pull request by Keith-CY**

### CODE REVIEW

**Comment by Keith-CY** [comment]
These updates would affect some functions:
1. functions of connecting to a ledger
2. block synchronization
3. process of packaging application

Please have a test after being merged @Cedar67

**Comment by Keith-CY** [comment]
> > These updates would affect some functions:
> > 
> > 1. functions of connecting to a ledger
> > 2. block synchronization
> > 3. process of packaging application
> > 
> > Please have a test after being merged @Cedar67
> 
> ok.

How is it going

**Comment by Cedar67** [comment]
> 



> > > These updates would affect some functions:
> > > 
> > > 1. functions of connecting to a ledger
> > > 2. block synchronization
> > > 3. process of packaging application
> > > 
> > > Please have a test after being merged @Cedar67
> > 
> > 
> > ok.
> 
> How is it going

Waiting for merge, then functional validation.

**Comment by Keith-CY** [comment]
> > 
> 
> > > > These updates would affect some functions:
> > > > 
> > > > 1. functions of connecting to a ledger
> > > > 2. block synchronization
> > > > 3. process of packaging application
> > > > 
> > > > Please have a test after being merged @Cedar67
> > > 
> > > 
> > > ok.
> > 
> > 
> > How is it going
> 
> Waiting for merge, then functional validation.

Got it

**Comment by Keith-CY** [comment]
@yanguoyu @JeffreyMa597 please have a review

**Review by yanguoyu — APPROVED** [review]

**Review by JeffreyMa597 — APPROVED** [review]

**Comment by Cedar67** [comment]
Verified in the `develop` branch.

**Pull request merged**
