### PR TITLE
Fix: offline sign not shown error message if broadcast error

### PR DESCRIPTION
**Pull request by devchenyan**
fix issue:
- https://github.com/Magickbase/neuron-public-issues/issues/221

https://github.com/nervosnetwork/neuron/assets/11756869/04fae799-861d-422f-9fcd-191c47e5fce1

### CODE REVIEW

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/blob/develop/packages/neuron-wallet/src/controllers/api.ts#L807-L843 has handled the exception, IMO we need not handle the exception additional in these functions.

**Review by yanguoyu — APPROVED** [review]

**Comment by Keith-CY** [comment]
The `yarn.lock` should not be updated in this PR

**Review by Keith-CY — APPROVED** [review]

**Comment by yanguoyu** [comment]
> /package Packageing failed in [5619166104](https://github.com/nervosnetwork/neuron/actions/runs/5619166104). @devchenyan

This PR has merged, so GitHub action can not get the PR branch. It can test by https://github.com/nervosnetwork/neuron/actions/runs/5619121856

**Pull request merged**
