### PR TITLE
fix: Set the bottom height max because bottom add an element

### PR DESCRIPTION
**Pull request by yanguoyu**
- before

image

- after

image

### CODE REVIEW

**Review by Keith-CY — APPROVED** [review]

**Comment by Keith-CY** [comment]
Please have a review @homura @WhiteMinds @devchenyan @silySuper

**Comment by silySuper** [comment]
The bug is still stay in  https://github.com/nervosnetwork/neuron/actions/runs/7707550848
截屏2024-01-31 09 51 42

**Comment by yanguoyu** [comment]
> The bug is still stay in https://github.com/nervosnetwork/neuron/actions/runs/7707550848 截屏2024-01-31 09 51 42

I guess you have used a wrong package, I have tried with  https://github.com/nervosnetwork/neuron/actions/runs/7707550848

image

**Comment by yanguoyu** [comment]
Sorry, My mistake, after closing the notice. It still exists.

**Comment by yanguoyu** [comment]
Fixed

**Review by silySuper — APPROVED** [review]

**Comment by Keith-CY** [comment]
Please have a review @homura @devchenyan @WhiteMinds

**Review by devchenyan — APPROVED** [review]

**Pull request merged**
