### PR TITLE
fix: Fix unmatched cheque lockHash

### PR DESCRIPTION
**Pull request by yanguoyu**

### CODE REVIEW

**Comment by Keith-CY** [comment]
Could you describe the bug in a little detail cuz it's too brief in the issue that I'm not clear about the it.

**Comment by yanguoyu** [comment]
> Could you describe the bug in a little detail cuz it's too brief in the issue that I'm not clear about it.
Detail on [this issue](https://github.com/Magickbase/neuron-internal/issues/1444).

**Comment by Keith-CY** [comment]
> > Could you describe the bug in a little detail cuz it's too brief in the issue that I'm not clear about it.
> > Detail on [this issue](https://github.com/Magickbase/neuron-internal/issues/1444).

I've viewed the issue but am not clear about the error.

```javascript
    const chequeCellTmp = Output.fromObject({
      capacity: BigInt(162 * 10 ** 8).toString(),
      lock: assetAccountInfo.generateChequeScript('0'.repeat(40), '0'.repeat(40)),
      type: assetAccountInfo.generateSudtScript(assetAccount.tokenID)
    })
   // ...
    const chequeCell = Output.fromObject({
      ...chequeCellTmp,
      data: BufferUtils.writeBigUInt128LE(BigInt(gatheredSudtInputResult.amount)),
      lock: assetAccountInfo.generateChequeScript(
        receiverLockScript.computeHash(),
        senderDefaultCell.lock!.computeHash()
      )
    })
```

`chequeCellTmp` is used as a placeholder of a cheque cell and its `lock` will be overridden by 
```javascript
assetAccountInfo.generateChequeScript(
  receiverLockScript.computeHash(),
  senderDefaultCell.lock!.computeHash()
)
```

and finally turns into

```javascript
{
  capacity: BigInt(162 * 10 ** 8).toString(),
  lock: assetAccountInfo.generateChequeScript(
    receiverLockScript.computeHash(),
    senderDefaultCell.lock!.computeHash()
  ),
  type: assetAccountInfo.generateSudtScript(assetAccount.tokenID),
  data: BufferUtils.writeBigUInt128LE(BigInt(gatheredSudtInputResult.amount)),
}
```
Which property is not correct

**Comment by yanguoyu** [comment]
> > > Could you describe the bug in a little detail cuz it's too brief in the issue that I'm not clear about it.
> > > Detail on [this issue](https://github.com/Magickbase/neuron-internal/issues/1444).
> 
> I've viewed the issue but am not clear about the error.
> 
> ```js
>     const chequeCellTmp = Output.fromObject({
>       capacity: BigInt(162 * 10 ** 8).toString(),
>       lock: assetAccountInfo.generateChequeScript('0'.repeat(40), '0'.repeat(40)),
>       type: assetAccountInfo.generateSudtScript(assetAccount.tokenID)
>     })
>    // ...
>     const chequeCell = Output.fromObject({
>       ...chequeCellTmp,
>       data: BufferUtils.writeBigUInt128LE(BigInt(gatheredSudtInputResult.amount)),
>       lock: assetAccountInfo.generateChequeScript(
>         receiverLockScript.computeHash(),
>         senderDefaultCell.lock!.computeHash()
>       )
>     })
> ```
> 
> `chequeCellTmp` is used as a placeholder of a cheque cell and its `lock` will be overridden by
> 
> ```js
> assetAccountInfo.generateChequeScript(
>   receiverLockScript.computeHash(),
>   senderDefaultCell.lock!.computeHash()
> )
> ```
> 
> and finally turns into
> 
> ```js
> {
>   capacity: BigInt(162 * 10 ** 8).toString(),
>   lock: assetAccountInfo.generateChequeScript(
>     receiverLockScript.computeHash(),
>     senderDefaultCell.lock!.computeHash()
>   ),
>   type: assetAccountInfo.generateSudtScript(assetAccount.tokenID),
>   data: BufferUtils.writeBigUInt128LE(BigInt(gatheredSudtInputResult.amount)),
> }
> ```
> 
> Which property is not correct

Output's lockHash is computed by `chequeCellTmp`'s lock, but not computed by `chequeCell `'s lock. So I set `chequeCell`'s lockHash `undefined`, so it can be computed again.

**Comment by Keith-CY** [comment]
> > > > Could you describe the bug in a little detail cuz it's too brief in the issue that I'm not clear about it.
> > > > Detail on [this issue](https://github.com/Magickbase/neuron-internal/issues/1444).
> > 
> > 
> > I've viewed the issue but am not clear about the error.
> > ```js
> >     const chequeCellTmp = Output.fromObject({
> >       capacity: BigInt(162 * 10 ** 8).toString(),
> >       lock: assetAccountInfo.generateChequeScript('0'.repeat(40), '0'.repeat(40)),
> >       type: assetAccountInfo.generateSudtScript(assetAccount.tokenID)
> >     })
> >    // ...
> >     const chequeCell = Output.fromObject({
> >       ...chequeCellTmp,
> >       data: BufferUtils.writeBigUInt128LE(BigInt(gatheredSudtInputResult.amount)),
> >       lock: assetAccountInfo.generateChequeScript(
> >         receiverLockScript.computeHash(),
> >         senderDefaultCell.lock!.computeHash()
> >       )
> >     })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > `chequeCellTmp` is used as a placeholder of a cheque cell and its `lock` will be overridden by
> > ```js
> > assetAccountInfo.generateChequeScript(
> >   receiverLockScript.computeHash(),
> >   senderDefaultCell.lock!.computeHash()
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and finally turns into
> > ```js
> > {
> >   capacity: BigInt(162 * 10 ** 8).toString(),
> >   lock: assetAccountInfo.generateChequeScript(
> >     receiverLockScript.computeHash(),
> >     senderDefaultCell.lock!.computeHash()
> >   ),
> >   type: assetAccountInfo.generateSudtScript(assetAccount.tokenID),
> >   data: BufferUtils.writeBigUInt128LE(BigInt(gatheredSudtInputResult.amount)),
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Which property is not correct
> 
> Output's lockHash is computed by `chequeCellTmp`'s lock, but not computed by `chequeCell `'s lock. So I set `chequeCell`'s lockHash `undefined`, so it can be computed again.

Got it

**Review by Keith-CY — APPROVED** [review]

**Review by qiweiii — APPROVED** [review]

**Pull request merged**
