### PR TITLE
refactor(neuron-wallet): move init app to app controller

### PR DESCRIPTION
**Pull request by Keith-CY**
and move change-language, set-application-menu from init-window method to init-app method

### CODE REVIEW

**Comment by Keith-CY** [comment]
> Why put init app logic in a controller ?

I regard the `ready` signal as a result of user input. Which tells the app to render UI(language, application menu).

Perhaps the `set network` should be put somewhere else.

**Comment by Keith-CY** [comment]
how about setting the network on node service initialization

**Comment by classicalliu** [comment]
I still confusing why `ready` signal is a user input event ?

**Comment by Keith-CY** [comment]
> I still confusing why `ready` signal is a user input event ?

Eventually, the `ready` action is triggered by the user action of opening the app.

**Pull request merged**
