### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by Keith-CY**
The following dependencies are going to be updated.

| Verification State | Dep Name&Desc                    |
| ------------------ | -------------------------------- |
| ✅                 | @babel/core                      |
| ✅                 | @storybook/\*                    |
| ✅                 | @types/node                      |
| ✅                 | @types/react                     |
| ✅                 | @types/react-dom                 |
| ✅                 | @types/styled-components         |
| ✅                 | @typescript-eslint/eslint-plugin |
| ✅                 | @typescript-eslint/parser        |
| ✅                 | actions/checkout                 |
| ✅                 | actions/github-script            |
| ✅                 | actions/setup-node               |
| ✅                 | actions/stale                    |
| ✅                 | actions/upload-artifact          |
| ✅                 | crazy-max/ghaction-import-gpg    |
| ✅                 | eslint                           |
| ✅                 | eslint-plugin-import             |
| ✅                 | i18next                          |
| ✅                 | react                            |
| ✅                 | react-dom                        |
| ✅                 | react-i18next                    |
| ✅                 | react-router-dom                 |
| ✅                 | react-test-renderer              |
| ✅                 | sass                             |
| ✅                 | storybook                        |
| ✅                 | undici                           |
| ✅                 | webpack                          |

### CODE REVIEW

**Comment by Keith-CY** [comment]
This PR includes major updates of React and it's better to merge it first

**Review by yanguoyu — APPROVED** [review]

**Comment by Keith-CY** [comment]
Please have a review @zhangyouxin @homura @WhiteMinds @devchenyan

**Review by homura — APPROVED** [review]

**Pull request merged**
