### PR TITLE
fix: Click current network button to switch type.

### PR DESCRIPTION
**Pull request by yanguoyu**
1. Click here to switch the network type, the tooltip is just a information
image

### CODE REVIEW

**Review by devchenyan — APPROVED** [review]

**Review by silySuper — APPROVED** [review]

**Comment by Keith-CY** [comment]
The interaction is changed here, and I'd like to know how it is supposed to be before.
It's probably about the feedback that `switch to mainnet` is hard to click, but it can be easily fixed by dismissing the tooltip a bit later.

**Comment by yanguoyu** [comment]
> The interaction is changed here, and I'd like to know how it is supposed to be before. It's probably about the feedback that `switch to mainnet` is hard to click, but it can be easily fixed by dismissing the tooltip a bit later.

Before switching network type by clicking the tooltip, now the tooltip only shows switch information, and click the current network type to switch it.

**Comment by Keith-CY** [comment]
> > The interaction is changed here, and I'd like to know how it is supposed to be before. It's probably about the feedback that `switch to mainnet` is hard to click, but it can be easily fixed by dismissing the tooltip a bit later.
> 
> Before switching network type by clicking the tooltip, now the tooltip only shows switch information, and click the current network type to switch it.

I got the change of interaction, but I wonder why. I ask this because
1. change of newly released UX implies that it's not fully polished
2. `switch to testnet` is not for general users, so it's better to be available in an implicit way. Placing it next to `switch to light client` is prone to click.
	- When light client is not selected, clicking on `light mainnet` will activate `light client mainnet`
	- When light client is selected, clicking on `light mainnet` will switch to `light client testnet`

I prefer a clear UX, with a clear `prompt` in the hot zone.

**Comment by Danie0918** [comment]
> > > The interaction is changed here, and I'd like to know how it is supposed to be before. It's probably about the feedback that `switch to mainnet` is hard to click, but it can be easily fixed by dismissing the tooltip a bit later.
> > 
> > 
> > Before switching network type by clicking the tooltip, now the tooltip only shows switch information, and click the current network type to switch it.
> 
> I got the change of interaction, but I wonder why. I ask this because
> 
> 1. change of newly released UX implies that it's not fully polished
> 2. `switch to testnet` is not for general users, so it's better to be available in an implicit way. Placing it next to `switch to light client` is prone to click.
>    
>    * When light client is not selected, clicking on `light mainnet` will activate `light client mainnet`
>    * When light client is selected, clicking on `light mainnet` will switch to `light client testnet`
> 
> I prefer a clear UX, with a clear `prompt` in the hot zone. cc @Danie0918

The main purpose here is to make it easy to switch between the built-in networks in order to research and experience the CKB network with the user. However, for users the network changes need to be more clearly prompted, this I communicate with Kirl.

**Comment by Danie0918** [comment]
> > > > The interaction is changed here, and I'd like to know how it is supposed to be before. It's probably about the feedback that `switch to mainnet` is hard to click, but it can be easily fixed by dismissing the tooltip a bit later.
> > > 
> > > 
> > > Before switching network type by clicking the tooltip, now the tooltip only shows switch information, and click the current network type to switch it.
> > 
> > 
> > I got the change of interaction, but I wonder why. I ask this because
> > 
> > 1. change of newly released UX implies that it's not fully polished
> > 2. `switch to testnet` is not for general users, so it's better to be available in an implicit way. Placing it next to `switch to light client` is prone to click.
> >    
> >    * When light client is not selected, clicking on `light mainnet` will activate `light client mainnet`
> >    * When light client is selected, clicking on `light mainnet` will switch to `light client testnet`
> > 
> > I prefer a clear UX, with a clear `prompt` in the hot zone. cc @Danie0918
> 
> The main purpose here is to make it easy to switch between the built-in networks in order to research and experience the CKB network with the user. However, for users the network changes need to be more clearly prompted, this I communicate with Kirl.

UI update:https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=28088%3A7597&mode=design&t=YIECbCV90dwff9JS-1

@yanguoyu @silySuper

**Comment by yanguoyu** [comment]
> > > > > The interaction is changed here, and I'd like to know how it is supposed to be before. It's probably about the feedback that `switch to mainnet` is hard to click, but it can be easily fixed by dismissing the tooltip a bit later.
> > > > 
> > > > 
> > > > Before switching network type by clicking the tooltip, now the tooltip only shows switch information, and click the current network type to switch it.
> > > 
> > > 
> > > I got the change of interaction, but I wonder why. I ask this because
> > > 
> > > 1. change of newly released UX implies that it's not fully polished
> > > 2. `switch to testnet` is not for general users, so it's better to be available in an implicit way. Placing it next to `switch to light client` is prone to click.
> > >    
> > >    * When light client is not selected, clicking on `light mainnet` will activate `light client mainnet`
> > >    * When light client is selected, clicking on `light mainnet` will switch to `light client testnet`
> > > 
> > > I prefer a clear UX, with a clear `prompt` in the hot zone. cc @Danie0918
> > 
> > 
> > The main purpose here is to make it easy to switch between the built-in networks in order to research and experience the CKB network with the user. However, for users the network changes need to be more clearly prompted, this I communicate with Kirl.
> 
> UI update:https://www.figma.com/file/6XNoimRDbFTTNm016rbIdU/Magickbase?type=design&node-id=28088%3A7597&mode=design&t=YIECbCV90dwff9JS-1
> 
> @yanguoyu @silySuper

@silySuper  update

**Review by Keith-CY — APPROVED** [review]

**Pull request merged**
