### PR TITLE
Merge master to develop

### PR DESCRIPTION
**Pull request by katat**

### CODE REVIEW

**Comment by katat** [comment]
@Keith-CY There are conflicts in the front end code. Could you please take a look and resolve it? 

Thanks

**Comment by Keith-CY** [comment]
I'll push a new branch to merge them

**Comment by Keith-CY** [comment]
🤔 It seems that 70% of conflicts happen in the `asset-account-service.test.ts`. I think it comes from the commits which merged in dev but squashed in rc.

**Comment by katat** [comment]
Thanks a lot for the heads-up and resolving these conflicts.

Once we got a chance, I would suggest we take a look together and see how we can avoid this type of code conflicts in the future.

**Pull request closed without merging**
