### PR TITLE
fix: Fix some exception from set ckb node path

### PR DESCRIPTION
**Pull request by yanguoyu**
1. Set ckb node data path to an empty directory, always delete mainnet ckb indexer data.
2. Delete ckb indexer data after start ckb to ensure ckb indexer data directory is correctly.

### CODE REVIEW

**Review by Keith-CY — APPROVED** [review]

**Comment by Cedar67** [comment]
> 1. Set ckb node data path to an empty directory, always delete mainnet ckb indexer data.
> 2. Delete ckb indexer data after start ckb to ensure ckb indexer data directory is correctly.

Verified.

**Comment by Cedar67** [comment]
Unexpected:
After manually started CKB nodes are stopped, Neuron cannot start internal CKB nodes normally.

https://user-images.githubusercontent.com/64718893/187120989-210a357c-6459-4abc-b355-965f6cc86a63.mov


image

**Comment by yanguoyu** [comment]
> Unexpected: After manually started CKB nodes are stopped, Neuron cannot start internal CKB nodes normally.
> 
>  20220829-120540-HD.mov 
> image

Upload bundled-ckb.log to help me why the ckb node stopped.

**Comment by Cedar67** [comment]
> > Unexpected: After manually started CKB nodes are stopped, Neuron cannot start internal CKB nodes normally.
> > 20220829-120540-HD.mov
> > image
> 
> Upload bundled-ckb.log to help me why the ckb node stopped.

@yanguoyu  FYI
[neuron_debug_1661744320528.zip](https://github.com/nervosnetwork/neuron/files/9442282/neuron_debug_1661744320528.zip)

**Comment by yanguoyu** [comment]
image

Maybe your ckb node is not completely stopped

**Comment by Cedar67** [comment]
> image
> 
> Maybe your ckb node is not completely stopped.

Looks like you were right about that.
When I stop CKB by Ctrl+Z in terminal, this exception will appear. The info displayed on the terminal shows that the CKB has been stopped, but the CKB process continues. Is this an approach we don't support by Neuron?

image

**Comment by yanguoyu** [comment]
> approach

Maybe you should try to use Ctrl + C to kill the ckb node process.

**Review by Cedar67 — APPROVED** [review]

**Pull request merged**
