### PR TITLE
Update SDK to v0.12.0 to support Rylai testnet

### PR DESCRIPTION
**Pull request by ashchan**
Rylai goes live 🍻

### CODE REVIEW

**Comment by ashchan** [comment]
@Keith-CY @classicalliu Please help on this see if there's any breaking changes that would apply.

I notice we've removed `tiny-secp256k1` from the SDK dependency. Unfortunately the `bip32` lib still relies on that. Wondering if we can write our own BIP32 module, or find another (secure and trust) library.

**Comment by classicalliu** [comment]
`OutPoint` structure changed

**Comment by ashchan** [comment]
> `OutPoint` structure changed

Feel free to amend directly to this branch.

**Comment by ashchan** [comment]
@classicalliu Yeah quite some changes, especially our DB related types. Could you please take care of them next week?

**Comment by classicalliu** [comment]
> @classicalliu Yeah quite some changes, especially our DB related types. Could you please take care of them next week?

I'll check

**Comment by ashchan** [comment]
Looks good.

**Pull request merged**
