### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by Keith-CY**
The following dependencies are going to be updated.

| Verification State | Dep Name&Desc                            |
| ------------------ | ---------------------------------------- |
| ✅                 | @babel/core                              |
| ✅                 | @babel/preset-typescript                 |
| ✅                 | @ckb-lumos/base                          |
| ✅                 | @ckb-lumos/bi                            |
| ✅                 | @ckb-lumos/ckb-indexer                   |
| ✅                 | @ckb-lumos/codec                         |
| ✅                 | @ckb-lumos/common-scripts                |
| ✅                 | @ckb-lumos/config-manager                |
| ✅                 | @ckb-lumos/hd                            |
| ✅                 | @ckb-lumos/helpers                       |
| ✅                 | @ckb-lumos/rpc                           |
| ✅                 | @jest/globals                            |
| ✅                 | @ledgerhq/hw-transport-node-hid          |
| ✅                 | @storybook/testing-library               |
| ✅                 | @types/npmlog                            |
| ✅                 | @types/enzyme                            |
| ✅                 | @types/enzyme-adapter-react-16           |
| ✅                 | @types/react                             |
| ✅                 | @types/react-dom                         |
| ✅                 | @types/styled-components                 |
| ✅                 | @types/async                             |
| ✅                 | @types/electron-devtools-installer       |
| ✅                 | @types/ellipsic                          |
| ✅                 | @types/iarna\_\_toml                     |
| ✅                 | @types/ledgerhq\_\_hw-transport          |
| ✅                 | @types/ledgerhq\_\_hw-transport-node-hid |
| ✅                 | @types/leveldown                         |
| ✅                 | @types/sqlite3                           |
| ✅                 | archiver                                 |
| ✅                 | async                                    |
| ✅                 | electron-notarize                        |
| ✅                 | electron                                 |
| ✅                 | concurrently                             |
| ✅                 | eslint                                   |
| ✅                 | eslint-config-prettier                   |
| ✅                 | typescript                               |

### CODE REVIEW

**Review by homura — APPROVED** [review]
LGTM

**Comment by Keith-CY** [comment]
> LGTM

I would like to add one more upgrade of https://github.com/Magickbase/neuron/pull/191 and then we may start the review

**Comment by Keith-CY** [comment]
Ready for review

**Review by yanguoyu — APPROVED** [review]

**Comment by yanguoyu** [comment]
/package
After updating the `@ledgerhq/hw-transport-node-hid`, we'd better check Neuron with the hard wallet. I will check with my `Ledger Nano S Plus`. Please test with your hard wallet. @silySuper  @FrederLu

**Comment by Keith-CY** [comment]
> /package After updating the `@ledgerhq/hw-transport-node-hid`, we'd better check Neuron with the hard wallet. I will check with my `Ledger Nano S Plus`. Please test with your hard wallet. @silySuper @FrederLu

I've verified with Ledger Nano X

**Comment by FrederLu** [comment]
> /package After updating the `@ledgerhq/hw-transport-node-hid`, we'd better check Neuron with the hard wallet. I will check with my `Ledger Nano S Plus`. Please test with your hard wallet. @silySuper @FrederLu

Ok, I'll use the hardware wallet to verify it after it's wrapped.

**Comment by yanguoyu** [comment]
Import the hard wallet with Ledger Nano S Plus failed. I will check the reason. 
From the log may find the device failed:
```
[2023-11-23T08:56:44.222Z] [info]  Find devices:	 [ [] ]
[2023-11-23T08:56:45.240Z] [info]  Find devices:	 [ [] ]
[2023-11-23T08:56:47.112Z] [info]  Find devices:	 [ [] ]
[2023-11-23T08:56:48.977Z] [info]  Find devices:	 [ [] ]
[2023-11-23T08:56:49.784Z] [info]  Find devices:	 [ [] ]
[2023-11-23T08:56:50.248Z] [info]  Database:	saved synced block #11379072
[2023-11-23T08:57:13.393Z] [info]  Find devices:	 [ [] ]
[2023-11-23T08:58:26.482Z] [info]  Database:	saved synced block #11379082
[2023-11-23T09:00:35.000Z] [info]  Database:	saved synced block #11379092
```
image

**Comment by FrederLu** [comment]
> Packaging for test is done in [6966219308](https://github.com/nervosnetwork/neuron/actions/runs/6966219308). @yanguoyu

When importing `Ledger Nano X`, I also encountered a prompt that the device cannot be detected.
image

**Comment by Keith-CY** [comment]
> /package Packaging for test is done in [6976112759](https://github.com/nervosnetwork/neuron/actions/runs/6976112759). @Keith-CY

Please verify `import a hardwallet` with this package @yanguoyu @FrederLu

**Comment by yanguoyu** [comment]
> > /package Packaging for test is done in [6976112759](https://github.com/nervosnetwork/neuron/actions/runs/6976112759). @Keith-CY
> 
> Please verify `import a hardwallet` with this package @yanguoyu @FrederLu

It works well with `Ledger Nano S Plus` on `import hard wallet`, `send`, `withdraw DAO`, and `deposit DAO`

**Comment by silySuper** [comment]
My device is same to yanguoyu(Ledger Nano S Plus).My package is the latest.
When I import hardware wallet it shows abnormal.It is my first time to use hardware wallet.
截屏2023-11-24 10 59 30

**Comment by yanguoyu** [comment]
> My device is same to yanguoyu(Ledger Nano S Plus).My package is the latest. When I import hardware wallet it shows abnormal.It is my first time to use hardware wallet. 截屏2023-11-24 10 59 30

Do you install and open the Nervos app on the device?

**Comment by silySuper** [comment]
> > My device is same to yanguoyu(Ledger Nano S Plus).My package is the latest. When I import hardware wallet it shows abnormal.It is my first time to use hardware wallet. 截屏2023-11-24 10 59 30
> 
> Do you install and open the Nervos app on the device?

no,OK,I will download  Nervos app.

**Comment by FrederLu** [comment]
> > /package Packaging for test is done in [6976112759](https://github.com/nervosnetwork/neuron/actions/runs/6976112759). @Keith-CY
> 
> Please verify `import a hardwallet` with this package @yanguoyu @FrederLu

image
The package can be imported into the hardware wallet normally, and transaction signatures are also normal.

**Comment by Keith-CY** [comment]
> > > /package Packaging for test is done in [6976112759](https://github.com/nervosnetwork/neuron/actions/runs/6976112759). @Keith-CY
> 
> > 
> 
> > Please verify `import a hardwallet` with this package @yanguoyu @FrederLu
> 
> 
> 
> image
> 
> 
> 
> The package can be imported into the hardware wallet normally, and transaction signatures are also normal.

Please add an approval if ledger works well with this update

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
