### PR TITLE
fix: Asset Accounts UI

### PR DESCRIPTION
**Pull request by devchenyan**
issue: https://github.com/Magickbase/neuron-public-issues/issues/423

fixed:
image

### CODE REVIEW

**Comment by Danie0918** [comment]
@Keith-CY @homura @yanguoyu  Please have a review.

**Review by homura — COMMENTED** [review]
Is the title "Undefined" as expected in the picture?

**Review by yanguoyu — APPROVED** [review]

**Comment by yanguoyu** [comment]
> Is the title "Undefined" as expected in the picture?

These SUDTs' information isn't set, so it shows as undefined. `Undefined` is a special value.

**Review by homura — APPROVED** [review]

**Review by silySuper — APPROVED** [review]

**Pull request merged**
