### PR TITLE
Bump some deps

### PR DESCRIPTION
**Pull request by Keith-CY**

### CODE REVIEW

**Comment by Keith-CY** [comment]
Among these updates, only `electron` and `sqlite3` may have impacts on functions.

I think we can merge these first and have a simple test to see if the app runs and if data are stored correctly. @yanguoyu @JeffreyMa597 @Cedar67

**Review by yanguoyu — APPROVED** [review]

**Comment by yanguoyu** [comment]
> Among these updates, only `electron` and `sqlite3` may have impacts on functions, they are so fundamental that it's easy to test.
> 
> I think we can merge these first and have a simple test to see if the app runs and if data are stored correctly. @yanguoyu @JeffreyMa597 @Cedar67

sure.

**Comment by Keith-CY** [comment]
I think this PR could be merged first and rely on the e2e tests to check if the app runs and if data are stored correctly, can we? @Cedar67

**Review by Cedar67 — APPROVED** [review]
Basic verification passed.

**Comment by Cedar67** [comment]
> I think this PR could be merged first and rely on the e2e tests to check if the app runs and if data are stored correctly, can we? @Cedar67

OK, It has been verified.

**Pull request merged**
