### PR TITLE
Resolve conflicts from master branch

### PR DESCRIPTION
**Pull request by katat**
For https://github.com/nervosnetwork/neuron/pull/1932

### CODE REVIEW

**Comment by Keith-CY** [comment]
I've tried 3 times but CI still failed.

**Comment by katat** [comment]
Yeah, somehow the dependency of `primereact.calendar` is not available anymore on either npm or yarn registry.

Screen Shot 2020-11-30 at 10 29 40 AM

**Comment by katat** [comment]
@Keith-CY Do you know the official website for this npm package? According to the npm package name, the closest I can find is https://bit.dev/primefaces/primereact/calendar/ but the packages in all versions are failed to be resolved. 

Is it the same as this one? https://www.primefaces.org/primereact/showcase/#/calendar

**Comment by Keith-CY** [comment]
> @Keith-CY Do you know the official website for this npm package? According to the npm package name, the closest I can find is [bit.dev/primefaces/primereact/calendar](https://bit.dev/primefaces/primereact/calendar/) but the packages in all versions are failed to be resolved.
> 
> Is it the same as this one? [primefaces.org/primereact/showcase/#/calendar](https://www.primefaces.org/primereact/showcase/#/calendar)

Yes, they are the same one.

**Comment by katat** [comment]
OK, could you please push updates to this branch for both the frontend dependency and the related code?

**Comment by Keith-CY** [comment]
> OK, could you please push updates to this branch for both the frontend dependency and the related code?

I'll update it today.

**Comment by katat** [comment]
I create a PR to resolve the primereact calendar package issue https://github.com/nervosnetwork/neuron/pull/1934

**Review by Keith-CY — APPROVED** [review]

**Review by kellyshang — APPROVED** [review]

**Pull request merged**
