### PR TITLE
fix: When set start block number is less than before, remove all of the sync data.

### PR DESCRIPTION
**Pull request by yanguoyu**
When we set a smaller number than before, the UI shows `The block number you set is smaller than the previous set, the synchronization will restart, please proceed with caution.` But actually, it does not remove all of the sync data.

`The last set startBlockNumber should be get before updating the wallet` will fix it.

### CODE REVIEW

**Review by Keith-CY — APPROVED** [review]

**Comment by yanguoyu** [comment]
@silySuper please test it.

**Comment by silySuper** [comment]
In my impression,start block number will effect by after clicking  clear all sync data ,can not effect after changed（I thought that was the logic before）.Now is effected after be changed.

**Review by silySuper — APPROVED** [review]

**Pull request merged**
