### PR TITLE
feat: use undici to replace axios

### PR DESCRIPTION
**Pull request by yanguoyu**
`undici` is created by Node.js org. Using it in Node.js is better.

### CODE REVIEW

**Comment by yanguoyu** [comment]
This PR may affect `multi sign` and `restart ckb indexer monitor`, need to test for these functions.

**Comment by Cedar67** [comment]
Unit test error.

**Comment by yanguoyu** [comment]
> Unit test error.

Fixed

**Review by Keith-CY — APPROVED** [review]

**Review by JeffreyMa597 — APPROVED** [review]

**Comment by Cedar67** [comment]
> This PR may affect `multi sign` and `restart ckb indexer monitor`, need to test for these functions.

Both of these functions have been verified.

**Review by Cedar67 — APPROVED** [review]

**Pull request merged**
