### PR TITLE
feat: Upgrade electron to 22.0.0

### PR DESCRIPTION
**Pull request by yanguoyu**
1. Remove `desktopCapturer` from the renderer process.
2. Set `nodeIntegration` to true because its default is false now.
3. Update `electron-log` to `4.4.8` because it throws an unhandled promise reject in 4.0.0.

### CODE REVIEW

**Review by Keith-CY — APPROVED** [review]

**Review by JeffreyMa597 — APPROVED** [review]

**Comment by Cedar67** [comment]
When click `Nervos DAO`, log displays an error message:

image

**Comment by yanguoyu** [comment]
> When click `Nervos DAO`, log displays an error message:
> 
> image

Can you expose the wallet public key, this problem may be related to the wallet.
I haven't received this problem.

**Comment by Cedar67** [comment]
> Can you expose the wallet public key, this problem may be related to the wallet.
> I haven't received this problem.

Please check the attachment to obtain the public key:
[Wallet AAA-xpubkey.json.zip](https://github.com/nervosnetwork/neuron/files/10322723/Wallet.AAA-xpubkey.json.zip)

**Comment by yanguoyu** [comment]
> > Can you expose the wallet public key, this problem may be related to the wallet.
> > I haven't received this problem.
> 
> Please check the attachment to obtain the public key: [Wallet AAA-xpubkey.json.zip](https://github.com/nervosnetwork/neuron/files/10322723/Wallet.AAA-xpubkey.json.zip)

I can't also reproduce this problem from your public key. From the screenshot, it causes by no unused address. Can you try to open your addresses page and find out whether there are no unused addresses?

**Comment by Keith-CY** [comment]
How is it going @Cedar67

**Review by Cedar67 — APPROVED** [review]
Verified.

**Pull request merged**
