### PR TITLE
feat: Adapt ckb light node (#2590)

### PR DESCRIPTION
**Pull request by Keith-CY**
[Screenshot 2023-05-18 at 01 47 24](http://www.youtube.com/watch?v=tQm9YvgG7iE)

https://youtu.be/tQm9YvgG7iE

----

> Using a MacBook Pro (13-inch, M1, 2020) device as an example, we realistically tested the synchronization from 0 to the latest block (2023/05/22 Pudge network data, excluding the time to find a trusted height):

> Light node: synchronization time about 5 hours and 30 minutes, data about 45M; (light client mode disk consumption is related to the number of account transactions, the test account a total of 782 transaction records)
Full node: about 36 hours for synchronization, about 107.8G of data;

> The above test data in the case of the same equipment and network, light node compared to full node synchronization time reduced 84.7% disk use reduced 99.9% (data for reference only, due to different equipment, network and account data, may be different from the experimental data)

Excerpt from https://github.com/Magickbase/neuron-public-issues/issues/138#issuecomment-1556688490

### CODE REVIEW

**Comment by Keith-CY** [comment]
CI failed at https://github.com/nervosnetwork/neuron/pull/2615/commits/e440f1b34e1e485a5151c52199ba1f7102c9d52d

**Comment by Keith-CY** [comment]
The blames at https://github.com/nervosnetwork/neuron/actions/runs/4760729869/jobs/8461313831#step:9:2115 blocks PR https://github.com/nervosnetwork/neuron/pull/2649

**Comment by yanguoyu** [comment]
> The blames at https://github.com/nervosnetwork/neuron/actions/runs/4760729869/jobs/8461313831#step:9:2115 blocks PR #2649

I fix the test case in the PR https://github.com/nervosnetwork/neuron/pull/2642, but it needs to wait for some reason. So I split the commit that fixes the test case to a new PR https://github.com/nervosnetwork/neuron/pull/2650.

**Comment by Keith-CY** [comment]
Light client mode has been verified by Acceptance team, and it can be merged into the release candidate for the full regression test. @yanguoyu @FrederLu

**Review by yanguoyu — APPROVED** [review]

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
