### PR TITLE
Rc/v0.34.0

### PR DESCRIPTION
**Pull request by kellyshang**
Plan to release v0.34.0 on 16th, Dec.

### CODE REVIEW

**Review by Keith-CY — APPROVED** [review]

**Review by yuche — APPROVED** [review]

**Comment by kellyshang** [comment]
hold on merge until v0.33.2 hotfix released.

**Comment by kellyshang** [comment]
@katat @Keith-CY @yuche this PR is reopened and please re-review it.

**Comment by katat** [comment]
Please see https://github.com/nervosnetwork/neuron/pull/1950 and https://github.com/nervosnetwork/neuron/pull/1951/ before merging into master.

**Comment by kellyshang** [comment]
> Please see #1950 and #1951 before merging into master.

the entrance of import hardware wallet should also be hidden on `Settings` window for production. @katat

**Comment by katat** [comment]
Got it @kellyshang. @Keith-CY Would you please take a look for this one, thanks.

**Comment by kellyshang** [comment]
> Got it @kellyshang. @Keith-CY Would you please take a look for this one, thanks.

My fault, it has been hidden for released package. Please ignore it.

**Review by katat — APPROVED** [review]

**Review by yuche — APPROVED** [review]

**Review by Keith-CY — APPROVED** [review]

**Pull request merged**
