### PR TITLE
fix: Init wallet device.

### PR DESCRIPTION
**Pull request by yanguoyu**
https://user-images.githubusercontent.com/12881040/216774832-9ee53446-bf33-418c-b5ed-9f1cf6525404.mov

### CODE REVIEW

**Review by Keith-CY — APPROVED** [review]

**Comment by Cedar67** [comment]
An error is found and needs to be located.

https://github.com/Magickbase/neuron-public-issues/issues/101#issuecomment-1419115837

**Comment by yanguoyu** [comment]
> fix: update electron and @ledgerhq/hw-transport-node-hid

Fixed with https://github.com/nervosnetwork/neuron/pull/2581/commits/e9b89392b1ba0f2c3804980e2a93f7937e7af17b.
After fetching new code, you need to run `yarn bootstrap` again and retry.

**Comment by yanguoyu** [comment]
> An error is found and needs to be located.
> 
> [Magickbase/neuron-public-issues#101 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/101#issuecomment-1419115837)

Fixed with https://github.com/nervosnetwork/neuron/commit/e9b89392b1ba0f2c3804980e2a93f7937e7af17b.
After fetching new code, you need to run yarn bootstrap again and retry.

**Comment by Cedar67** [comment]
> > An error is found and needs to be located.
> > [Magickbase/neuron-public-issues#101 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/101#issuecomment-1419115837)
> 
> Fixed with [e9b8939](https://github.com/nervosnetwork/neuron/commit/e9b89392b1ba0f2c3804980e2a93f7937e7af17b). After fetching new code, you need to run yarn bootstrap again and retry.

After clicking **`sign`**, a new error message is displayed.
The cause of the problem needs to be further located with App v0.5.5 in NanoX.

image

**Comment by Keith-CY** [comment]
> > > An error is found and needs to be located.
> > > [Magickbase/neuron-public-issues#101 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/101#issuecomment-1419115837)
> > 
> > 
> > Fixed with [e9b8939](https://github.com/nervosnetwork/neuron/commit/e9b89392b1ba0f2c3804980e2a93f7937e7af17b). After fetching new code, you need to run yarn bootstrap again and retry.
> 
> After clicking **`sign`**, a new error message is displayed. The cause of the problem needs to be further located with App v0.5.5 in NanoX.
> 
> image

Similar to https://github.com/nervosnetwork/neuron/issues/2583

**Comment by Keith-CY** [comment]
> > > An error is found and needs to be located.
> > > [Magickbase/neuron-public-issues#101 (comment)](https://github.com/Magickbase/neuron-public-issues/issues/101#issuecomment-1419115837)
> > 
> > 
> > Fixed with [e9b8939](https://github.com/nervosnetwork/neuron/commit/e9b89392b1ba0f2c3804980e2a93f7937e7af17b). After fetching new code, you need to run yarn bootstrap again and retry.
> 
> After clicking **`sign`**, a new error message is displayed. The cause of the problem needs to be further located with App v0.5.5 in NanoX.
> 
> image

Is this error reproducible since we found `address for` should be set to `mainnet`? @Cedar67

**Review by JeffreyMa597 — APPROVED** [review]

**Comment by yanguoyu** [comment]
From https://github.com/LedgerHQ/ledger-live/issues/2583#issuecomment-1442544299, I guess `getVersion` will return success when we don't open any App on `ledger`. So when we open `Nervos`, it will throw an exception is normal.

https://user-images.githubusercontent.com/12881040/221074301-abbd2edb-04d4-4cb5-aec4-0d8df8104f62.mov

**Comment by Cedar67** [comment]
> 
> Is this error reproducible since we found `address for` should be set to `mainnet`? @Cedar67

This error is not reproducible now.

**Comment by Cedar67** [comment]
> From [LedgerHQ/ledger-live#2583 (comment)](https://github.com/LedgerHQ/ledger-live/issues/2583#issuecomment-1442544299), I guess `getVersion` will return success when we don't open any App on `ledger`. So when we open `Nervos`, it will throw an exception is normal.

Is throwing this exception prompt as expected when the CKB App is not open on Ledger? @yanguoyu 

image

**Comment by yanguoyu** [comment]
> > From [LedgerHQ/ledger-live#2583 (comment)](https://github.com/LedgerHQ/ledger-live/issues/2583#issuecomment-1442544299), I guess `getVersion` will return success when we don't open any App on `ledger`. So when we open `Nervos`, it will throw an exception is normal.
> 
> Is throwing this exception prompt as expected when the CKB App is not open on Ledger? @yanguoyu
> 
> image

From my video, I guess yes.

**Comment by Keith-CY** [comment]
How is it being tested @Cedar67

**Review by Cedar67 — APPROVED** [review]
Verified.
Environment:
Nano X
CKB app v0.5.5

**Pull request merged**
