### PR TITLE
feat(neuron-ui): update the cycles on the outputs changing

### PR DESCRIPTION
**Pull request by Keith-CY**
@classicalliu please implement the `calculateCycles` method in the wallet controller

### CODE REVIEW

**Comment by ashchan** [comment]
Holding this til we have a clear solution to this feature.

**Comment by ashchan** [comment]
Please un-hold this when we have the cycle related calculation (just works is enough, no need to be perfect) implemented.

**Comment by Keith-CY** [comment]
TODO: format methods require more tests

**Comment by Keith-CY** [comment]
@ashchan @classicalliu Ready for review

**Pull request merged**
