### PR TITLE
fix: Setting font for linux

### PR DESCRIPTION
**Pull request by yanguoyu**
1. mac
      - zh  <br />image
      - en  image

2. Windows
      - zh <br />image

      - en <br />image

3. Linux
      - zh <br /> image
      - en <br /> image

### CODE REVIEW

**Comment by yanguoyu** [comment]
@Kirl70 please help me check whether these fonts display is normal.

**Comment by Kirl70** [comment]
> @Kirl70 please help me check whether these fonts display is normal.

I think the font display meets expectations.

**Review by Keith-CY — APPROVED** [review]

**Review by devchenyan — APPROVED** [review]

**Comment by Keith-CY** [comment]
Verified on Linux

**Pull request merged**
