### PR TITLE
feat: Displaying DAO rewards

### PR DESCRIPTION
**Pull request by devchenyan**
issue: https://github.com/Magickbase/neuron-public-issues/issues/317

https://github.com/nervosnetwork/neuron/assets/11756869/cdd70b32-b3dd-418f-a41c-f76d09e3faa1

### CODE REVIEW

**Review by yanguoyu — APPROVED** [review]

**Comment by Danie0918** [comment]
@homura Please have a review.

**Review by homura — APPROVED** [review]

**Comment by silySuper** [comment]
The package above shows error and  always shows connecting ：
截屏2024-04-01 15 36 30

 [error] Export Debug:	 export public key info error: ConnectionIsNotSetError: Connection with sqlite database is not established. Check connection configuration.

**Comment by silySuper** [comment]
I  have tried  as this before.Maybe this operation affect sync.
截屏2024-04-02 15 10 06

I have replace cells  file to old version,the sync process shows 100%.

**Comment by silySuper** [comment]
1.Have enough balance,but shows insufficient balance.

https://github.com/nervosnetwork/neuron/assets/25971273/9f71fb4a-c70a-492d-bcd0-262251bec8aa

**Review by silySuper — APPROVED** [review]

**Pull request merged**
