### PR TITLE
fix: Migrate legacy acp to new acp account

### PR DESCRIPTION
**Pull request by yanguoyu**
Refer to https://github.com/Magickbase/neuron-public-issues/issues/360
Support migrating legacy ACP to the new or existing account, add cell dep when migrating legacy ACP cell. Remove migrated legacy ACP dialog.

1. Migrate to new

https://github.com/nervosnetwork/neuron/assets/12881040/e53148aa-97e8-48da-8e0d-2bb871b65e92

2. Migrate to exist

https://github.com/nervosnetwork/neuron/assets/12881040/aa43e963-16c1-410e-959f-bf2a29cb5f9e

Here is the wallet that includes legacy ACP sudt cell

image

### CODE REVIEW

**Comment by Danie0918** [comment]
@homura @devchenyan Please have a review.

**Review by devchenyan — APPROVED** [review]

**Review by homura — APPROVED** [review]

**Comment by yanguoyu** [comment]
> 1.dialog is still stay. 截屏2024-04-30 16 56 37
> 

I guess you do not use the right package, I downloaded the package and it does not show the dialog. And the words in your picture are not used in this PR.

**Review by silySuper — APPROVED** [review]

**Pull request merged**
