### PR TITLE
chore(neuron-ui): add react hooks rules

### PR DESCRIPTION
**Pull request by Keith-CY**

### CODE REVIEW

**Comment by ashchan** [comment]
Menu: Next release of `react-scripts` will include this plugin by default.

**Comment by ashchan** [comment]
@Keith-CY Another thing: this plugin was added to `neuron-ui` package; but we have other aslint plugins on the root package. (In fact `react` related plugins should go to `neuron-ui` package but `airbnb` depends on `eslint-plugin-react`, `eslint-plugin-jsx-a11y` and others so we just place them there. 😿

**Comment by Keith-CY** [comment]
> @Keith-CY Another thing: this plugin was added to `neuron-ui` package; but we have other aslint plugins on the root package. (In fact `react` related plugins should go to `neuron-ui` package but `airbnb` depends on `eslint-plugin-react`, `eslint-plugin-jsx-a11y` and others so we just place them there. 😿

[eslint-config-airbnb](https://github.com/airbnb/javascript) is a general eslint preset working for any JavaScript Projects so it also works for `neuron-wallet`, we can install it in `neuron-wallet` and `neuron-ui`, respectively, but react-related eslint-plugn-xx will be added to `neuron-wallet` too.

**Comment by ashchan** [comment]
Yes. My point is we use it as a general preset but it actually requires `eslint-plugin-react` already.

**Comment by Keith-CY** [comment]
> Yes. My point is we use it as a general preset but it actually requires `eslint-plugin-react` already.

I've got that. We can use [eslint-config-airbnb-base](https://www.npmjs.com/package/eslint-config-airbnb-base) at the root and move React-related to `neuron-ui`.

**Pull request merged**
