### PR TITLE
feat:Detect new upgrade on launch

### PR DESCRIPTION
**Pull request by yanguoyu**
1. No update both starting and checking by manual

https://github.com/nervosnetwork/neuron/assets/12881040/6219a87c-d2a9-4b57-b6b3-a9f2caf0d438

2. No update when starting but has update when checking by manual

https://github.com/nervosnetwork/neuron/assets/12881040/28f2e2f3-c256-45ed-80e8-4b51303f89e8

3. Has update when starting

https://github.com/nervosnetwork/neuron/assets/12881040/9ffe0e6c-6659-4204-8733-7a1e7e3a5d39

### CODE REVIEW

**Review by devchenyan — APPROVED** [review]

**Review by WhiteMinds — APPROVED** [review]

**Comment by yanguoyu** [comment]
https://github.com/nervosnetwork/neuron/actions/runs/5687806837 @silySuper for case 2

**Comment by silySuper** [comment]
1.Verified，pass
2.Does no update when starting but has update when checking by manual  should revert to the previous state, which is to show the old version when cancel update in   midway @Danie0918 ？
3.The same as https://github.com/nervosnetwork/neuron/pull/2787

**Comment by Danie0918** [comment]
> 2.Does no update when starting but has update when checking by manual should revert to the previous state, which is to show the old version when cancel update in midway @Danie0918 ？ 

In this case, if a new version is fetched, the new version should be displayed.

**Comment by silySuper** [comment]
Bugs link: https://github.com/Magickbase/neuron-public-issues/issues/251
After fix and confirm these bugs I will approve this issue~

**Comment by yanguoyu** [comment]
> Bugs link: [Magickbase/neuron-public-issues#251](https://github.com/Magickbase/neuron-public-issues/issues/251) After fix and confirm these bugs I will approve this issue~

The bug has fixed and package again, you can get the packages from the PR comment.

**Review by silySuper — APPROVED** [review]

**Pull request merged**
