### PR TITLE
fix: Style issue with multisig addresses

### PR DESCRIPTION
**Pull request by devchenyan**
fix: 
- https://github.com/Magickbase/neuron-public-issues/issues/266

### CODE REVIEW

**Review by yanguoyu — APPROVED** [review]

**Review by zhangyouxin — APPROVED** [review]

**Review by zhangyouxin — APPROVED** [review]

**Review by WhiteMinds — APPROVED** [review]

**Comment by yanguoyu** [comment]
@devchenyan  The test case run failed.

**Review by FrederLu — APPROVED** [review]

**Pull request merged**
